# Generated by Django 2.2.1 on 2020-01-03 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=50)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2020, 1, 3, 18, 54, 5, 694330, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ismi')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Fan')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charachteristics', models.CharField(blank=True, max_length=100, verbose_name="Ta'rif")),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='FISH')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='Telefoni nomeri')),
                ('fathers_phone', models.CharField(blank=True, max_length=100, verbose_name='Otasing telefoni')),
                ('mothers_phone', models.CharField(blank=True, max_length=100, verbose_name='Onasing telefoni')),
                ('teacher', models.ManyToManyField(related_name='students', to='payment.Teacher', verbose_name="o'qituvchisi")),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('percent', models.IntegerField(default=50)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Teacher', verbose_name="o'qituvchi")),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Student', verbose_name="o'quvchisi"),
        ),
        migrations.AddField(
            model_name='contract',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Teacher', verbose_name="o'qituvchisi"),
        ),
    ]
