# Generated by Django 2.2.1 on 2020-01-03 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 19, 37, 50, 408455, tzinfo=utc)),
        ),
    ]
