# Generated by Django 2.2.1 on 2020-01-05 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200104_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 15, 46, 43, 537677, tzinfo=utc)),
        ),
    ]
