# Generated by Django 2.2.1 on 2020-01-05 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200105_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 15, 54, 36, 838748, tzinfo=utc)),
        ),
    ]
