# Generated by Django 2.2.1 on 2020-01-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200105_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
