# Generated by Django 2.2.1 on 2020-01-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200105_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='contract',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Student', verbose_name="o'quvchisi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Teacher', verbose_name="o'qituvchisi"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
