# Generated by Django 2.2.1 on 2020-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200115_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2020),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="san'a"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='percent',
            field=models.IntegerField(default=50, verbose_name='foiz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FISH'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ismi'),
        ),
    ]
