# Generated by Django 2.2.1 on 2020-01-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20200123_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="san'a"),
        ),
        migrations.AlterField(
            model_name='student',
            name='charachteristics',
            field=models.CharField(blank=True, max_length=30, verbose_name="Ta'rif"),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=50)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='payment.Student', verbose_name="o'quvchisi")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='payment.Teacher', verbose_name="o'qituvchisi")),
            ],
        ),
    ]
