# Generated by Django 2.2.1 on 2020-01-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200130_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Contract'),
            preserve_default=False,
        ),
    ]
