# Generated by Django 2.2.1 on 2020-01-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='charachteristics',
            field=models.TextField(blank=True, max_length=30, verbose_name="Ta'rif"),
        ),
    ]
