# Generated by Django 2.2.1 on 2020-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20200130_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fathers_phone',
            field=models.CharField(default='-', max_length=20, verbose_name='Otasing tel.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_phone',
            field=models.CharField(default='-', max_length=20, verbose_name='Onasing tel.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='-', max_length=20, verbose_name='Tel. nomeri'),
        ),
    ]
