# Generated by Django 2.2.1 on 2020-01-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20200131_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='has_to_pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('teacher', 'student')},
        ),
    ]
