# Generated by Django 2.2.1 on 2020-01-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20200201_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('teacher', 'student', 'period')},
        ),
    ]
