# Generated by Django 2.2 on 2020-02-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20200201_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lovlar", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterField(
            model_name='payment',
            name='has_to_pay',
            field=models.IntegerField(default=0, verbose_name="To'lanishi kerak"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.IntegerField(default=0, verbose_name="To'landi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.CharField(choices=[('Yanvar 2020', 'Yanvar 2020'), ('Fevral 2020', 'Fevral 2020'), ('Mart 2020', 'Mart 2020'), ('Aprel 2020', 'Aprel 2020'), ('May 2020', 'May 2020'), ('Iyun 2020', 'Iyun 2020'), ('Iyul 2020', 'Iyul 2020'), ('Avgust 2020', 'Avgust 2020'), ('Sentyabr 2020', 'Sentyabr 2020'), ('Oktyabr 2020', 'Oktyabr 2020'), ('Noyabr 2020', 'Noyabr 2020'), ('Dekabr 2020', 'Dekabr 2020'), ('Yanvar 2021', 'Yanvar 2021'), ('Fevral 2021', 'Fevral 2021'), ('Mart 2021', 'Mart 2021'), ('Aprel 2021', 'Aprel 2021'), ('May 2021', 'May 2021'), ('Iyun 2021', 'Iyun 2021'), ('Iyul 2021', 'Iyul 2021'), ('Avgust 2021', 'Avgust 2021'), ('Sentyabr 2021', 'Sentyabr 2021'), ('Oktyabr 2021', 'Oktyabr 2021'), ('Noyabr 2021', 'Noyabr 2021'), ('Dekabr 2021', 'Dekabr 2021'), ('Yanvar 2022', 'Yanvar 2022'), ('Fevral 2022', 'Fevral 2022'), ('Mart 2022', 'Mart 2022'), ('Aprel 2022', 'Aprel 2022'), ('May 2022', 'May 2022'), ('Iyun 2022', 'Iyun 2022'), ('Iyul 2022', 'Iyul 2022'), ('Avgust 2022', 'Avgust 2022'), ('Sentyabr 2022', 'Sentyabr 2022'), ('Oktyabr 2022', 'Oktyabr 2022'), ('Noyabr 2022', 'Noyabr 2022'), ('Dekabr 2022', 'Dekabr 2022'), ('Yanvar 2023', 'Yanvar 2023'), ('Fevral 2023', 'Fevral 2023'), ('Mart 2023', 'Mart 2023'), ('Aprel 2023', 'Aprel 2023'), ('May 2023', 'May 2023'), ('Iyun 2023', 'Iyun 2023'), ('Iyul 2023', 'Iyul 2023'), ('Avgust 2023', 'Avgust 2023'), ('Sentyabr 2023', 'Sentyabr 2023'), ('Oktyabr 2023', 'Oktyabr 2023'), ('Noyabr 2023', 'Noyabr 2023'), ('Dekabr 2023', 'Dekabr 2023'), ('Yanvar 2024', 'Yanvar 2024'), ('Fevral 2024', 'Fevral 2024'), ('Mart 2024', 'Mart 2024'), ('Aprel 2024', 'Aprel 2024'), ('May 2024', 'May 2024'), ('Iyun 2024', 'Iyun 2024'), ('Iyul 2024', 'Iyul 2024'), ('Avgust 2024', 'Avgust 2024'), ('Sentyabr 2024', 'Sentyabr 2024'), ('Oktyabr 2024', 'Oktyabr 2024'), ('Noyabr 2024', 'Noyabr 2024'), ('Dekabr 2024', 'Dekabr 2024'), ('Yanvar 2025', 'Yanvar 2025'), ('Fevral 2025', 'Fevral 2025'), ('Mart 2025', 'Mart 2025'), ('Aprel 2025', 'Aprel 2025'), ('May 2025', 'May 2025'), ('Iyun 2025', 'Iyun 2025'), ('Iyul 2025', 'Iyul 2025'), ('Avgust 2025', 'Avgust 2025'), ('Sentyabr 2025', 'Sentyabr 2025'), ('Oktyabr 2025', 'Oktyabr 2025'), ('Noyabr 2025', 'Noyabr 2025'), ('Dekabr 2025', 'Dekabr 2025')], default='Fevral 2020', max_length=20, verbose_name="To'lov oyi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathers_phone',
            field=models.CharField(blank=True, default='-', max_length=20, verbose_name='Otasing tel.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_phone',
            field=models.CharField(blank=True, default='-', max_length=20, verbose_name='Onasing tel.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=20, verbose_name='Tel. nomeri'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Yanvar 2020', 'Yanvar 2020'), ('Fevral 2020', 'Fevral 2020'), ('Mart 2020', 'Mart 2020'), ('Aprel 2020', 'Aprel 2020'), ('May 2020', 'May 2020'), ('Iyun 2020', 'Iyun 2020'), ('Iyul 2020', 'Iyul 2020'), ('Avgust 2020', 'Avgust 2020'), ('Sentyabr 2020', 'Sentyabr 2020'), ('Oktyabr 2020', 'Oktyabr 2020'), ('Noyabr 2020', 'Noyabr 2020'), ('Dekabr 2020', 'Dekabr 2020'), ('Yanvar 2021', 'Yanvar 2021'), ('Fevral 2021', 'Fevral 2021'), ('Mart 2021', 'Mart 2021'), ('Aprel 2021', 'Aprel 2021'), ('May 2021', 'May 2021'), ('Iyun 2021', 'Iyun 2021'), ('Iyul 2021', 'Iyul 2021'), ('Avgust 2021', 'Avgust 2021'), ('Sentyabr 2021', 'Sentyabr 2021'), ('Oktyabr 2021', 'Oktyabr 2021'), ('Noyabr 2021', 'Noyabr 2021'), ('Dekabr 2021', 'Dekabr 2021'), ('Yanvar 2022', 'Yanvar 2022'), ('Fevral 2022', 'Fevral 2022'), ('Mart 2022', 'Mart 2022'), ('Aprel 2022', 'Aprel 2022'), ('May 2022', 'May 2022'), ('Iyun 2022', 'Iyun 2022'), ('Iyul 2022', 'Iyul 2022'), ('Avgust 2022', 'Avgust 2022'), ('Sentyabr 2022', 'Sentyabr 2022'), ('Oktyabr 2022', 'Oktyabr 2022'), ('Noyabr 2022', 'Noyabr 2022'), ('Dekabr 2022', 'Dekabr 2022'), ('Yanvar 2023', 'Yanvar 2023'), ('Fevral 2023', 'Fevral 2023'), ('Mart 2023', 'Mart 2023'), ('Aprel 2023', 'Aprel 2023'), ('May 2023', 'May 2023'), ('Iyun 2023', 'Iyun 2023'), ('Iyul 2023', 'Iyul 2023'), ('Avgust 2023', 'Avgust 2023'), ('Sentyabr 2023', 'Sentyabr 2023'), ('Oktyabr 2023', 'Oktyabr 2023'), ('Noyabr 2023', 'Noyabr 2023'), ('Dekabr 2023', 'Dekabr 2023'), ('Yanvar 2024', 'Yanvar 2024'), ('Fevral 2024', 'Fevral 2024'), ('Mart 2024', 'Mart 2024'), ('Aprel 2024', 'Aprel 2024'), ('May 2024', 'May 2024'), ('Iyun 2024', 'Iyun 2024'), ('Iyul 2024', 'Iyul 2024'), ('Avgust 2024', 'Avgust 2024'), ('Sentyabr 2024', 'Sentyabr 2024'), ('Oktyabr 2024', 'Oktyabr 2024'), ('Noyabr 2024', 'Noyabr 2024'), ('Dekabr 2024', 'Dekabr 2024'), ('Yanvar 2025', 'Yanvar 2025'), ('Fevral 2025', 'Fevral 2025'), ('Mart 2025', 'Mart 2025'), ('Aprel 2025', 'Aprel 2025'), ('May 2025', 'May 2025'), ('Iyun 2025', 'Iyun 2025'), ('Iyul 2025', 'Iyul 2025'), ('Avgust 2025', 'Avgust 2025'), ('Sentyabr 2025', 'Sentyabr 2025'), ('Oktyabr 2025', 'Oktyabr 2025'), ('Noyabr 2025', 'Noyabr 2025'), ('Dekabr 2025', 'Dekabr 2025')], default='Fevral 2020', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="to'langan san'a")),
                ('paid', models.IntegerField(default=0, verbose_name='Hisoblandi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='payment.Teacher')),
            ],
        ),
    ]
