# Generated by Django 2.2 on 2020-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20200206_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Shartnoma', 'verbose_name_plural': 'Shartnomalar'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Oylik', 'verbose_name_plural': 'Oyliklar'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='group',
        ),
        migrations.AddField(
            model_name='contract',
            name='group_time',
            field=models.CharField(choices=[('6.00', '6.00'), ('7.00', '7.00'), ('8.00', '8.00'), ('9.00', '9.00'), ('10.00', '10.00'), ('11.00', '11.00'), ('12.00', '12.00'), ('13.00', '13.00'), ('14.00', '14.00'), ('15.00', '15.00'), ('16.00', '16.00'), ('17.00', '17.00'), ('18.00', '18.00'), ('19.00', '19.00'), ('20.00', '20.00'), ('21.00', '21.00'), ('22.00', '22.00'), ('23.00', '23.00')], default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='parity',
            field=models.CharField(choices=[('Toq', 'Toq'), ('Juft', 'Juft')], default=1, max_length=5, verbose_name='Kun'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
