# Generated by Django 2.2 on 2020-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20200206_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='official',
            field=models.IntegerField(default=0, verbose_name='rasmiy oylik'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='official',
            field=models.IntegerField(default=0, verbose_name='rasmiy oylik'),
        ),
    ]
