# Generated by Django 2.2 on 2020-02-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20200209_2135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('teacher', 'period')},
        ),
    ]
