# Generated by Django 2.2 on 2020-02-14 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_user_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0020_auto_20200210_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='kassir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
            preserve_default=False,
        ),
    ]
