# Generated by Django 2.2 on 2020-02-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20200214_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
