# Generated by Django 2.2 on 2020-02-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20200214_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
        ),
    ]
