# Generated by Django 2.2 on 2020-02-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_auto_20200215_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Ishchi', 'verbose_name_plural': 'Ishchilar'},
        ),
    ]
